# Generated by Django 3.1.2 on 2021-03-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery_Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=12)),
                ('item_quantity', models.IntegerField()),
                ('item_status', models.CharField(choices=[('pending', 'pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
