# Generated by Django 3.1.2 on 2021-03-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery_bag',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='grocery_bag',
            name='item_status',
            field=models.CharField(choices=[('Bought', 'Bought'), ('Not AVAILABLE', 'Not AVAILABLE'), ('PENDING', 'PENDING')], max_length=200, null=True),
        ),
    ]
